language: python
python:
    - "2.7"
env:
    - PGVERSION=9.1 CKANVERSION=master
    - PGVERSION=9.1 CKANVERSION=2.3
    - PGVERSION=9.1 CKANVERSION=2.4.0
install:
    - bash bin/travis-build.bash
    - pip install coveralls -U
script: sh bin/travis-run.sh
after_success:
    - coveralls
