language: python
python:
    - "2.7"
env:
    - CKAN_BRANCH=master
    - CKAN_BRANCH=release-v2.3-latest
    - CKAN_BRANCH=release-v2.4-latest
    - CKAN_BRANCH=release-v2.5-latest
install:
    - bash bin/travis-build.bash
    - pip install coveralls -U
services:
    - postgresql
script: sh bin/travis-run.sh
after_success:
    - coveralls
